### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by ikatza** [rrwen/cookiecutter-latex#1]
I'm trying to use your template but can't get it to work. I've tried using different fields for the questions and just using the default values, but alas nothing is being produced. The traceback is not really useful and would seem to point out to an error with Jinja or something else. However I've used other cookie cutters with no problem.

I suspect there's an extra `{` or `}` somewhere, but can't really find it.

Below the whole traceback output. 

```
author [Richard Wen]:
email [rrwen.dev@gmail.com]:
Select include_email:
1 - yes
2 - no
Choose from 1, 2 (1, 2) [1]:
template_name [template_name]:
template_description [template_description]:
github_user [rrwen]:
github_url [https://github.com/rrwen/template_name]:
github_short [rrwen/template_name]:
tex_title [tex_title]:
Select tex_titlepage:
1 - yes
2 - no
Choose from 1, 2 (1, 2) [1]:
tex_firstname [Richard]:
tex_lastname [Wen]:
tex_affil [Department of Civil Engineering \ Ryerson University \ Toronto, ON]:
tex_year [2019]:
tex_short [template_name]:
tex_file [richard_wen_2019_template_name]:
Select tex_fontsize:
1 - 12pt
2 - 11pt
3 - 10pt
Choose from 1, 2, 3 (1, 2, 3) [1]:
tex_fontstyle [Times New Roman]:
tex_margin [1in]:
tex_imagefolder [./img/]:
tex_imageformats [.pdf,.png]:
Select include_footer:
1 - yes
2 - no
Choose from 1, 2 (1, 2) [1]:
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/main.py", line 82, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/prompt.py", line 232, in prompt_for_config
    val = render_variable(env, raw, cookiecutter_dict)
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/prompt.py", line 160, in render_variable
    for k, v in raw.items()
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/prompt.py", line 160, in <dictcomp>
    for k, v in raw.items()
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/prompt.py", line 170, in render_variable
    template = env.from_string(raw)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 620, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 500, in parse_math1
    right = self.parse_concat()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 581, in parse_primary
    node = self.parse_dict()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 661, in parse_dict
    key = self.parse_expression()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 450, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 459, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 470, in parse_not
    return self.parse_compare()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 546, in parse_unary
    node = self.parse_primary()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 581, in parse_primary
    node = self.parse_dict()
  File "/usr/local/lib/python3.7/site-packages/jinja2/parser.py", line 662, in parse_dict
    self.stream.expect('colon')
  File "/usr/local/lib/python3.7/site-packages/jinja2/lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
```

**Comment by josephdanna** [comment]
I get the same exact error

**Comment by kierun** [comment]
2025… Still the same error. ¯\\\_(ツ)\_/¯
